### ISSUE TITLE
Storage class name not being used in the PVC templates

### ISSUE THREAD

**Issue by imgios** [fonzdm/servarr#17]
### Description

Seems like that the storage class named passed in the values `global.storageClassName` is not being used correctly when creating the PVC, so Kubernetes uses the default storage class.

I think that's because there's a typo when referring to the parameter:

https://github.com/fonzdm/servarr/blob/d08a0a606a7cdd5f0d3c51ecfa9901c597643fa4/servarr/templates/pvc.yaml#L12

https://github.com/fonzdm/servarr/blob/d08a0a606a7cdd5f0d3c51ecfa9901c597643fa4/servarr/templates/pvc.yaml#L33

https://github.com/fonzdm/servarr/blob/d08a0a606a7cdd5f0d3c51ecfa9901c597643fa4/servarr/templates/pvc.yaml#L54

### Steps to reproduce

- Clone the repository from the main or dev branches
- Execute the following command from within the folder `helm template servarr servarr/ -f .github/ci/ci-values.yaml | egrep -i "servarr/templates/pvc.yaml|storageClassName"` or deploy it using your values.

### Expected behavior

The Helm Chart should generate PVC templates using the correct `StorageClassName` from the values.

### Servarr Helm Chart version

dev

### Relevant log output

```shell
~$ helm template servarr servarr/servarr/ -f test/servarr-values.yaml | egrep -i "servarr/templates/|storageClassName"
# Source: servarr/templates/pvc.yaml
  storageClassName:
# Source: servarr/templates/pvc.yaml
  storageClassName:
# Source: servarr/templates/pvc.yaml
  storageClassName:
```

### Chart values

```yaml
# Check .github/ci/ci-values.yaml
global:
  storageClassName: &storageClassName "longhorn"

...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrgionsi** [comment]
Hi @imgios, @fonzdm ,

I will take this and will try to fix it! 😄

**Comment by imgios** [comment]
> Hi @imgios, @fonzdm ,
> 
> I will take this and will try to fix it! 😄

Welcome aboard!

Feel free to create your first contribution, just make sure you read the [guidelines](https://github.com/fonzdm/servarr/blob/main/CONTRIBUTING.md) 😊

**Comment by fonzdm** [comment]
> Hi @imgios, @fonzdm ,
> 
> I will take this and will try to fix it! 😄 

Hi @mrgionsi, please go ahead! 💪🏻

**Comment by imgios** [comment]
Issue fixed in #18. Thanks again, @mrgionsi!

**Comment by emouawad** [comment]
This is still happening on latest `1.0.1`
Note i haven't downloaded the chart - maybe that's the reason yaml anchors are not working?
Why are yaml anchors needed anyway? in helm this is not needed

```yaml
helm upgrade -i --namespace servarr --create-namespace --repo https://fonzdm.github.io/servarr --values values.yml servarr servarr --debug
```
```yaml
global:
  apikey: &apikey "aaa-bbb-ccc-ddd"
  storageClassName: &storageClassName "longhorn"
  ingressClassName: &ingressClassName "nginx"
  certManagerClusterIssuer: &issuer "clusterissuer-self-signed"

metrics:
  enabled: &metricsEnabled false
```

**Comment by imgios** [comment]
Hi @emouawad, thanks for the feedback. Can you please [open a separated issue](https://github.com/fonzdm/servarr/issues/new?assignees=&labels=bug%2Cneeds+triage&projects=&template=bug.yaml)? I will link it to this one.
